////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2018 Garmin Canada Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 20.72Release
// Tag = production/akw/20.72.00-0-g2c26d20
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class GarminProduct {
    public static final int HRM1 = 1;
    public static final int AXH01 = 2; // AXH01 HRM chipset
    public static final int AXB01 = 3;
    public static final int AXB02 = 4;
    public static final int HRM2SS = 5;
    public static final int DSI_ALF02 = 6;
    public static final int HRM3SS = 7;
    public static final int HRM_RUN_SINGLE_BYTE_PRODUCT_ID = 8; // hrm_run model for HRM ANT+ messaging
    public static final int BSM = 9; // BSM model for ANT+ messaging
    public static final int BCM = 10; // BCM model for ANT+ messaging
    public static final int AXS01 = 11; // AXS01 HRM Bike Chipset model for ANT+ messaging
    public static final int HRM_TRI_SINGLE_BYTE_PRODUCT_ID = 12; // hrm_tri model for HRM ANT+ messaging
    public static final int FR225_SINGLE_BYTE_PRODUCT_ID = 14; // fr225 model for HRM ANT+ messaging
    public static final int FR301_CHINA = 473;
    public static final int FR301_JAPAN = 474;
    public static final int FR301_KOREA = 475;
    public static final int FR301_TAIWAN = 494;
    public static final int FR405 = 717; // Forerunner 405
    public static final int FR50 = 782; // Forerunner 50
    public static final int FR405_JAPAN = 987;
    public static final int FR60 = 988; // Forerunner 60
    public static final int DSI_ALF01 = 1011;
    public static final int FR310XT = 1018; // Forerunner 310
    public static final int EDGE500 = 1036;
    public static final int FR110 = 1124; // Forerunner 110
    public static final int EDGE800 = 1169;
    public static final int EDGE500_TAIWAN = 1199;
    public static final int EDGE500_JAPAN = 1213;
    public static final int CHIRP = 1253;
    public static final int FR110_JAPAN = 1274;
    public static final int EDGE200 = 1325;
    public static final int FR910XT = 1328;
    public static final int EDGE800_TAIWAN = 1333;
    public static final int EDGE800_JAPAN = 1334;
    public static final int ALF04 = 1341;
    public static final int FR610 = 1345;
    public static final int FR210_JAPAN = 1360;
    public static final int VECTOR_SS = 1380;
    public static final int VECTOR_CP = 1381;
    public static final int EDGE800_CHINA = 1386;
    public static final int EDGE500_CHINA = 1387;
    public static final int FR610_JAPAN = 1410;
    public static final int EDGE500_KOREA = 1422;
    public static final int FR70 = 1436;
    public static final int FR310XT_4T = 1446;
    public static final int AMX = 1461;
    public static final int FR10 = 1482;
    public static final int EDGE800_KOREA = 1497;
    public static final int SWIM = 1499;
    public static final int FR910XT_CHINA = 1537;
    public static final int FENIX = 1551;
    public static final int EDGE200_TAIWAN = 1555;
    public static final int EDGE510 = 1561;
    public static final int EDGE810 = 1567;
    public static final int TEMPE = 1570;
    public static final int FR910XT_JAPAN = 1600;
    public static final int FR620 = 1623;
    public static final int FR220 = 1632;
    public static final int FR910XT_KOREA = 1664;
    public static final int FR10_JAPAN = 1688;
    public static final int EDGE810_JAPAN = 1721;
    public static final int VIRB_ELITE = 1735;
    public static final int EDGE_TOURING = 1736; // Also Edge Touring Plus
    public static final int EDGE510_JAPAN = 1742;
    public static final int HRM_TRI = 1743;
    public static final int HRM_RUN = 1752;
    public static final int FR920XT = 1765;
    public static final int EDGE510_ASIA = 1821;
    public static final int EDGE810_CHINA = 1822;
    public static final int EDGE810_TAIWAN = 1823;
    public static final int EDGE1000 = 1836;
    public static final int VIVO_FIT = 1837;
    public static final int VIRB_REMOTE = 1853;
    public static final int VIVO_KI = 1885;
    public static final int FR15 = 1903;
    public static final int VIVO_ACTIVE = 1907;
    public static final int EDGE510_KOREA = 1918;
    public static final int FR620_JAPAN = 1928;
    public static final int FR620_CHINA = 1929;
    public static final int FR220_JAPAN = 1930;
    public static final int FR220_CHINA = 1931;
    public static final int APPROACH_S6 = 1936;
    public static final int VIVO_SMART = 1956;
    public static final int FENIX2 = 1967;
    public static final int EPIX = 1988;
    public static final int FENIX3 = 2050;
    public static final int EDGE1000_TAIWAN = 2052;
    public static final int EDGE1000_JAPAN = 2053;
    public static final int FR15_JAPAN = 2061;
    public static final int EDGE520 = 2067;
    public static final int EDGE1000_CHINA = 2070;
    public static final int FR620_RUSSIA = 2072;
    public static final int FR220_RUSSIA = 2073;
    public static final int VECTOR_S = 2079;
    public static final int EDGE1000_KOREA = 2100;
    public static final int FR920XT_TAIWAN = 2130;
    public static final int FR920XT_CHINA = 2131;
    public static final int FR920XT_JAPAN = 2132;
    public static final int VIRBX = 2134;
    public static final int VIVO_SMART_APAC = 2135;
    public static final int ETREX_TOUCH = 2140;
    public static final int EDGE25 = 2147;
    public static final int FR25 = 2148;
    public static final int VIVO_FIT2 = 2150;
    public static final int FR225 = 2153;
    public static final int FR630 = 2156;
    public static final int FR230 = 2157;
    public static final int VIVO_ACTIVE_APAC = 2160;
    public static final int VECTOR_2 = 2161;
    public static final int VECTOR_2S = 2162;
    public static final int VIRBXE = 2172;
    public static final int FR620_TAIWAN = 2173;
    public static final int FR220_TAIWAN = 2174;
    public static final int TRUSWING = 2175;
    public static final int FENIX3_CHINA = 2188;
    public static final int FENIX3_TWN = 2189;
    public static final int VARIA_HEADLIGHT = 2192;
    public static final int VARIA_TAILLIGHT_OLD = 2193;
    public static final int EDGE_EXPLORE_1000 = 2204;
    public static final int FR225_ASIA = 2219;
    public static final int VARIA_RADAR_TAILLIGHT = 2225;
    public static final int VARIA_RADAR_DISPLAY = 2226;
    public static final int EDGE20 = 2238;
    public static final int D2_BRAVO = 2262;
    public static final int APPROACH_S20 = 2266;
    public static final int VARIA_REMOTE = 2276;
    public static final int HRM4_RUN = 2327;
    public static final int VIVO_ACTIVE_HR = 2337;
    public static final int VIVO_SMART_GPS_HR = 2347;
    public static final int VIVO_SMART_HR = 2348;
    public static final int VIVO_MOVE = 2368;
    public static final int VARIA_VISION = 2398;
    public static final int VIVO_FIT3 = 2406;
    public static final int FENIX3_HR = 2413;
    public static final int VIRB_ULTRA_30 = 2417;
    public static final int INDEX_SMART_SCALE = 2429;
    public static final int FR235 = 2431;
    public static final int FENIX3_CHRONOS = 2432;
    public static final int OREGON7XX = 2441;
    public static final int RINO7XX = 2444;
    public static final int NAUTIX = 2496;
    public static final int EDGE_820 = 2530;
    public static final int EDGE_EXPLORE_820 = 2531;
    public static final int FENIX5S = 2544;
    public static final int D2_BRAVO_TITANIUM = 2547;
    public static final int VARIA_UT800 = 2567; // Varia UT 800 SW
    public static final int RUNNING_DYNAMICS_POD = 2593;
    public static final int FENIX5X = 2604;
    public static final int VIVO_FIT_JR = 2606;
    public static final int FR935 = 2691;
    public static final int FENIX5 = 2697;
    public static final int SDM4 = 10007; // SDM4 footpod
    public static final int EDGE_REMOTE = 10014;
    public static final int TRAINING_CENTER = 20119;
    public static final int CONNECTIQ_SIMULATOR = 65531;
    public static final int ANDROID_ANTPLUS_PLUGIN = 65532;
    public static final int CONNECT = 65534; // Garmin Connect website
    public static final int INVALID = Fit.UINT16_INVALID;

    private static final Map<Integer, String> stringMap;

    static {
        stringMap = new HashMap<Integer, String>();
        stringMap.put(HRM1, "HRM1");
        stringMap.put(AXH01, "AXH01");
        stringMap.put(AXB01, "AXB01");
        stringMap.put(AXB02, "AXB02");
        stringMap.put(HRM2SS, "HRM2SS");
        stringMap.put(DSI_ALF02, "DSI_ALF02");
        stringMap.put(HRM3SS, "HRM3SS");
        stringMap.put(HRM_RUN_SINGLE_BYTE_PRODUCT_ID, "HRM_RUN_SINGLE_BYTE_PRODUCT_ID");
        stringMap.put(BSM, "BSM");
        stringMap.put(BCM, "BCM");
        stringMap.put(AXS01, "AXS01");
        stringMap.put(HRM_TRI_SINGLE_BYTE_PRODUCT_ID, "HRM_TRI_SINGLE_BYTE_PRODUCT_ID");
        stringMap.put(FR225_SINGLE_BYTE_PRODUCT_ID, "FR225_SINGLE_BYTE_PRODUCT_ID");
        stringMap.put(FR301_CHINA, "FR301_CHINA");
        stringMap.put(FR301_JAPAN, "FR301_JAPAN");
        stringMap.put(FR301_KOREA, "FR301_KOREA");
        stringMap.put(FR301_TAIWAN, "FR301_TAIWAN");
        stringMap.put(FR405, "FR405");
        stringMap.put(FR50, "FR50");
        stringMap.put(FR405_JAPAN, "FR405_JAPAN");
        stringMap.put(FR60, "FR60");
        stringMap.put(DSI_ALF01, "DSI_ALF01");
        stringMap.put(FR310XT, "FR310XT");
        stringMap.put(EDGE500, "EDGE500");
        stringMap.put(FR110, "FR110");
        stringMap.put(EDGE800, "EDGE800");
        stringMap.put(EDGE500_TAIWAN, "EDGE500_TAIWAN");
        stringMap.put(EDGE500_JAPAN, "EDGE500_JAPAN");
        stringMap.put(CHIRP, "CHIRP");
        stringMap.put(FR110_JAPAN, "FR110_JAPAN");
        stringMap.put(EDGE200, "EDGE200");
        stringMap.put(FR910XT, "FR910XT");
        stringMap.put(EDGE800_TAIWAN, "EDGE800_TAIWAN");
        stringMap.put(EDGE800_JAPAN, "EDGE800_JAPAN");
        stringMap.put(ALF04, "ALF04");
        stringMap.put(FR610, "FR610");
        stringMap.put(FR210_JAPAN, "FR210_JAPAN");
        stringMap.put(VECTOR_SS, "VECTOR_SS");
        stringMap.put(VECTOR_CP, "VECTOR_CP");
        stringMap.put(EDGE800_CHINA, "EDGE800_CHINA");
        stringMap.put(EDGE500_CHINA, "EDGE500_CHINA");
        stringMap.put(FR610_JAPAN, "FR610_JAPAN");
        stringMap.put(EDGE500_KOREA, "EDGE500_KOREA");
        stringMap.put(FR70, "FR70");
        stringMap.put(FR310XT_4T, "FR310XT_4T");
        stringMap.put(AMX, "AMX");
        stringMap.put(FR10, "FR10");
        stringMap.put(EDGE800_KOREA, "EDGE800_KOREA");
        stringMap.put(SWIM, "SWIM");
        stringMap.put(FR910XT_CHINA, "FR910XT_CHINA");
        stringMap.put(FENIX, "FENIX");
        stringMap.put(EDGE200_TAIWAN, "EDGE200_TAIWAN");
        stringMap.put(EDGE510, "EDGE510");
        stringMap.put(EDGE810, "EDGE810");
        stringMap.put(TEMPE, "TEMPE");
        stringMap.put(FR910XT_JAPAN, "FR910XT_JAPAN");
        stringMap.put(FR620, "FR620");
        stringMap.put(FR220, "FR220");
        stringMap.put(FR910XT_KOREA, "FR910XT_KOREA");
        stringMap.put(FR10_JAPAN, "FR10_JAPAN");
        stringMap.put(EDGE810_JAPAN, "EDGE810_JAPAN");
        stringMap.put(VIRB_ELITE, "VIRB_ELITE");
        stringMap.put(EDGE_TOURING, "EDGE_TOURING");
        stringMap.put(EDGE510_JAPAN, "EDGE510_JAPAN");
        stringMap.put(HRM_TRI, "HRM_TRI");
        stringMap.put(HRM_RUN, "HRM_RUN");
        stringMap.put(FR920XT, "FR920XT");
        stringMap.put(EDGE510_ASIA, "EDGE510_ASIA");
        stringMap.put(EDGE810_CHINA, "EDGE810_CHINA");
        stringMap.put(EDGE810_TAIWAN, "EDGE810_TAIWAN");
        stringMap.put(EDGE1000, "EDGE1000");
        stringMap.put(VIVO_FIT, "VIVO_FIT");
        stringMap.put(VIRB_REMOTE, "VIRB_REMOTE");
        stringMap.put(VIVO_KI, "VIVO_KI");
        stringMap.put(FR15, "FR15");
        stringMap.put(VIVO_ACTIVE, "VIVO_ACTIVE");
        stringMap.put(EDGE510_KOREA, "EDGE510_KOREA");
        stringMap.put(FR620_JAPAN, "FR620_JAPAN");
        stringMap.put(FR620_CHINA, "FR620_CHINA");
        stringMap.put(FR220_JAPAN, "FR220_JAPAN");
        stringMap.put(FR220_CHINA, "FR220_CHINA");
        stringMap.put(APPROACH_S6, "APPROACH_S6");
        stringMap.put(VIVO_SMART, "VIVO_SMART");
        stringMap.put(FENIX2, "FENIX2");
        stringMap.put(EPIX, "EPIX");
        stringMap.put(FENIX3, "FENIX3");
        stringMap.put(EDGE1000_TAIWAN, "EDGE1000_TAIWAN");
        stringMap.put(EDGE1000_JAPAN, "EDGE1000_JAPAN");
        stringMap.put(FR15_JAPAN, "FR15_JAPAN");
        stringMap.put(EDGE520, "EDGE520");
        stringMap.put(EDGE1000_CHINA, "EDGE1000_CHINA");
        stringMap.put(FR620_RUSSIA, "FR620_RUSSIA");
        stringMap.put(FR220_RUSSIA, "FR220_RUSSIA");
        stringMap.put(VECTOR_S, "VECTOR_S");
        stringMap.put(EDGE1000_KOREA, "EDGE1000_KOREA");
        stringMap.put(FR920XT_TAIWAN, "FR920XT_TAIWAN");
        stringMap.put(FR920XT_CHINA, "FR920XT_CHINA");
        stringMap.put(FR920XT_JAPAN, "FR920XT_JAPAN");
        stringMap.put(VIRBX, "VIRBX");
        stringMap.put(VIVO_SMART_APAC, "VIVO_SMART_APAC");
        stringMap.put(ETREX_TOUCH, "ETREX_TOUCH");
        stringMap.put(EDGE25, "EDGE25");
        stringMap.put(FR25, "FR25");
        stringMap.put(VIVO_FIT2, "VIVO_FIT2");
        stringMap.put(FR225, "FR225");
        stringMap.put(FR630, "FR630");
        stringMap.put(FR230, "FR230");
        stringMap.put(VIVO_ACTIVE_APAC, "VIVO_ACTIVE_APAC");
        stringMap.put(VECTOR_2, "VECTOR_2");
        stringMap.put(VECTOR_2S, "VECTOR_2S");
        stringMap.put(VIRBXE, "VIRBXE");
        stringMap.put(FR620_TAIWAN, "FR620_TAIWAN");
        stringMap.put(FR220_TAIWAN, "FR220_TAIWAN");
        stringMap.put(TRUSWING, "TRUSWING");
        stringMap.put(FENIX3_CHINA, "FENIX3_CHINA");
        stringMap.put(FENIX3_TWN, "FENIX3_TWN");
        stringMap.put(VARIA_HEADLIGHT, "VARIA_HEADLIGHT");
        stringMap.put(VARIA_TAILLIGHT_OLD, "VARIA_TAILLIGHT_OLD");
        stringMap.put(EDGE_EXPLORE_1000, "EDGE_EXPLORE_1000");
        stringMap.put(FR225_ASIA, "FR225_ASIA");
        stringMap.put(VARIA_RADAR_TAILLIGHT, "VARIA_RADAR_TAILLIGHT");
        stringMap.put(VARIA_RADAR_DISPLAY, "VARIA_RADAR_DISPLAY");
        stringMap.put(EDGE20, "EDGE20");
        stringMap.put(D2_BRAVO, "D2_BRAVO");
        stringMap.put(APPROACH_S20, "APPROACH_S20");
        stringMap.put(VARIA_REMOTE, "VARIA_REMOTE");
        stringMap.put(HRM4_RUN, "HRM4_RUN");
        stringMap.put(VIVO_ACTIVE_HR, "VIVO_ACTIVE_HR");
        stringMap.put(VIVO_SMART_GPS_HR, "VIVO_SMART_GPS_HR");
        stringMap.put(VIVO_SMART_HR, "VIVO_SMART_HR");
        stringMap.put(VIVO_MOVE, "VIVO_MOVE");
        stringMap.put(VARIA_VISION, "VARIA_VISION");
        stringMap.put(VIVO_FIT3, "VIVO_FIT3");
        stringMap.put(FENIX3_HR, "FENIX3_HR");
        stringMap.put(VIRB_ULTRA_30, "VIRB_ULTRA_30");
        stringMap.put(INDEX_SMART_SCALE, "INDEX_SMART_SCALE");
        stringMap.put(FR235, "FR235");
        stringMap.put(FENIX3_CHRONOS, "FENIX3_CHRONOS");
        stringMap.put(OREGON7XX, "OREGON7XX");
        stringMap.put(RINO7XX, "RINO7XX");
        stringMap.put(NAUTIX, "NAUTIX");
        stringMap.put(EDGE_820, "EDGE_820");
        stringMap.put(EDGE_EXPLORE_820, "EDGE_EXPLORE_820");
        stringMap.put(FENIX5S, "FENIX5S");
        stringMap.put(D2_BRAVO_TITANIUM, "D2_BRAVO_TITANIUM");
        stringMap.put(VARIA_UT800, "VARIA_UT800");
        stringMap.put(RUNNING_DYNAMICS_POD, "RUNNING_DYNAMICS_POD");
        stringMap.put(FENIX5X, "FENIX5X");
        stringMap.put(VIVO_FIT_JR, "VIVO_FIT_JR");
        stringMap.put(FR935, "FR935");
        stringMap.put(FENIX5, "FENIX5");
        stringMap.put(SDM4, "SDM4");
        stringMap.put(EDGE_REMOTE, "EDGE_REMOTE");
        stringMap.put(TRAINING_CENTER, "TRAINING_CENTER");
        stringMap.put(CONNECTIQ_SIMULATOR, "CONNECTIQ_SIMULATOR");
        stringMap.put(ANDROID_ANTPLUS_PLUGIN, "ANDROID_ANTPLUS_PLUGIN");
        stringMap.put(CONNECT, "CONNECT");
    }


    /**
     * Retrieves the String Representation of the Value
     * @return The string representation of the value, or empty if unknown
     */
    public static String getStringFromValue( Integer value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Retrieves a value given a string representation
     * @return The value or INVALID if unkwown
     */
    public static Integer getValueFromString( String value ) {
        for( Map.Entry<Integer, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
